### PR TITLE
README - Typo 115200 ! 105200

### PR DESCRIPTION
**Pull request by baylanger**
This sure looks like a typo. Feel free to merge this PR or update the value in a later PR.

### CODE REVIEW

**Comment by ArminJo** [comment]
Thank you very much for reporting 👍 
I amended the fix to the Documentation commit

**Comment by baylanger** [comment]
@ArminJo ... I was looking at your last PR that included my change.

```
Power is taken from an USB power supply connected to the Nano. Current is 40 mA for a dark 2004 display and 55 mA for a bright one.
{snip}
Or use a reliable buck converters for 55V, but they may be hard to find.
```

Is this 55V or 5V? If 55V where is that from?

ps: I'm not using your project yet... was looking at a solar inverter that is compatible w/ Pylontech, so the reason I was looking around for such projects.

**Comment by ArminJo** [comment]
Thanks for asking!!!
`Or use the complete battery voltage for Nano supply, but a reliable buck converters for around 50 to 60 volt may be hard to find.`

**Comment by baylanger** [comment]
Ok, I think now I understand. Pylontech battery banks are 48V LFP and this is where the 50-60VDC comes from. I am guessing that all products compatible with Pylontech are at 48V LFP?  If I'm wrong let me know :)

I faced a similar issue building my own ATS (automatic transfer switch) and needed to power a small device. I bought this [buck converter](https://www.aliexpress.com/item/1005006151847010.html) on Ali. It covers a very wide range of voltage and 5V@3A. 3A is overkill but it should last long too to supply a small Nano.

**Pull request closed without merging**
